### PR TITLE
Upgrade support table

### PR DESCRIPTION
**Pull request by AnninoDr4**

### CODE REVIEW

**Comment by SaicharanKandukuri** [comment]
its good idea
also we need to map documentation links to install them

**Review by SaicharanKandukuri — CHANGES_REQUESTED** [review]
Map installation documentation link

**Comment by AnninoDr4** [comment]
> Map installation documentation link

Ok
to udroid-wiki

**Review by SaicharanKandukuri — APPROVED** [review]
looks good

**Pull request merged**
